spring.application.name=myLabrary


spring.datasource.url=jdbc:postgressql://localhost:5434/library_db
spring.datasource.username=postgres
spring.datasource.password=root



spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true

